### PR TITLE
Solves problem when process hangs on S3 fetch

### PR DESCRIPTION
**Pull request by dpgaspar**
... and another on, minor changes this time, but fixes process hang if S3 list_objects fails.

Thanks!

### CODE REVIEW

**Comment by dpgaspar** [comment]
Could you please merge this one? It would greatly simplify my deploy process.

Thanks again

**Comment by kubihie** [comment]
mearged!

**Comment by kubihie** [comment]
sorry for being late

**Comment by dpgaspar** [comment]
No problem! thank you for your work.

**Comment by dpgaspar** [comment]
Sorry, could you please publish it, so i can use it with td-agent-gem install?

**Comment by kubihie** [comment]
v0.0.5 released.
it contain your commit.
thanks!

**Pull request merged**
